---
model_fields:
  mark:
    to_meta: False
    col_width: 80
    edit: True
    view: ['patient', 'organism', 'lab']
    checkable: True
    delegates: ['checkbox']
    model_validators: False
    paste_validators: False
  internal_lab_id:
    to_meta: True
    col_width: 120
    edit: False
    view: ['patient', 'organism', 'lab']
    checkable: False
    delegates: ['None']
    model_validators: ['distinct']
    paste_validators: False
  selection_criterion:
    to_meta: True
    col_width: 200
    edit: True
    view: ['patient']
    checkable: False
    delegates: ['combobox']
    model_validators: ['len5']
    paste_validators: False
  collection_date:
    to_meta: True
    col_width: 130
    edit: True
    view: ['patient']
    checkable: False
    delegates: ['date']
    model_validators: ['date_format']
    paste_validators: False
  patient_age:
    to_meta: True
    col_width: 120
    edit: True
    view: [ 'patient' ]
    checkable: False
    delegates: ['age']
    model_validators: ['age_range']
    paste_validators: False
  patient_sex:
    to_meta: True
    col_width: 120
    edit: True
    view: [ 'patient' ]
    checkable: False
    delegates: ['combobox']
    model_validators: ['inlist']
    paste_validators: False
  patient_status:
    to_meta: True
    col_width: 150
    edit: True
    view: [ 'patient' ]
    checkable: False
    delegates: ['combobox']
    model_validators: ['inlist']
    paste_validators: False
  type:
    to_meta: True
    col_width: 100
    edit: True
    view: [ 'patient' ]
    checkable: False
    delegates: ['combobox']
    model_validators: ['inlist']
    paste_validators: False
  sminet_lid:
    to_meta: True
    col_width: 100
    edit: True
    view: [ 'lab' ]
    checkable: False
    delegates: [ 'None' ]
    model_validators: False
    paste_validators: False
  pseudo_id:
    to_meta: True
    col_width: 200
    edit: False
    view: ['None']
    checkable: False
    delegates: ['None']
    model_validators: ['distinct']
    paste_validators: False
  region:
    to_meta: True
    col_width: 200
    edit: True
    view: ['lab']
    checkable: False
    delegates: ['combobox']
    model_validators: ['inlist']
    paste_validators: False
  region_code:
    to_meta: True
    col_width: 200
    edit: True
    view: ['None']
    checkable: False
    delegates: ['None']
    model_validators: ['inlist']
    paste_validators: False
  lab:
    to_meta: True
    col_width: 150
    edit: True
    view: ['None']
    checkable: False
    delegates: ['None']
    model_validators: ['inlist']
    paste_validators: False
  lab_code:
    to_meta: True
    col_width: 150
    edit: True
    view: [ 'None' ]
    checkable: False
    delegates: [ 'None' ]
    model_validators: ['inlist']
    paste_validators: False
  host:
    to_meta: True
    col_width: 100
    edit: True
    view: ['None']
    checkable: False
    delegates: ['None']
    model_validators: ['len5']
    paste_validators: False
  passage_details:
    to_meta: True
    col_width: 130
    edit: True
    view: [ 'organism' ]
    checkable: False
    delegates: ['None']
    model_validators: False
    paste_validators: False
  seq_technology:
    to_meta: True
    col_width: 150
    edit: True
    view: ['None']
    checkable: False
    delegates: ['None']
    model_validators: ['inlist']
    paste_validators: False
  library_method:
    to_meta: True
    col_width: 150
    edit: True
    view: ['None']
    checkable: False
    delegates: ['None']
    model_validators: ['inlist']
    paste_validators: False
  lane:
    to_meta: True
    col_width: 80
    edit: False
    view: ['lab']
    checkable: False
    delegates: ['None']
    model_validators: False
    paste_validators: False
  fastq:
    to_meta: True
    col_width: 100
    edit: False
    view: ['lab']
    checkable: False
    delegates: ['None']
    model_validators: False
    paste_validators: False
  fast5:
    to_meta: True
    col_width: 100
    edit: False
    view: [ 'lab' ]
    checkable: False
    delegates: ['None']
    model_validators: False
    paste_validators: False
  seq_path:
    to_meta: False
    col_width: 200
    edit: False
    view: ['lab']
    checkable: False
    delegates: ['None']
    model_validators: False
    paste_validators: False
  comment:
    to_meta: True
    col_width: 200
    edit: True
    view: ['patient', 'organism', 'lab']
    checkable: False
    delegates: ['None']
    model_validators: False
    paste_validators: False

settings_structure:
  - label: "Submitter"
    target_layout: form
    items:
      - entered_value:
        - submitter
  - label: "Paths"
    target_layout: form
    items:
      - entered_value:
        - seq_base_path
        - csv_base_path
        - metadata_output_path
        - metadata_docs_path
  - label: "Import/paste fx"
    target_layout: form
    items:
      - select_single:
        - fx
  - label: "Metadata preset"
    target_layout: form
    items:
    - select_single:
      - lab
      - seq_technology
      - host
      - library_method
  - label: "Metadata accepted values"
    target_layout: tabs
    items:
    - select_multi:
      - region
      - selection_criterion
      - patient_sex
      - passage_details_history
      - type
      - patient_status
  - label: "Upload connection"
    target_layout: form
    items:
      - entered_value:
        - credentials_path
      - select_single:
        - target_label
  - label: "PseudoID"
    target_layout: form
    items:
      - entered_value:
        - pseudo_id_filepath

settings_values:
  entered_value:
    seq_base_path: None
    csv_base_path: None
    metadata_output_path: None
    metadata_docs_path: None
    pseudo_id_filepath: None
    credentials_path: None
    submitter: None
  select_single:
    target_label: None
    fx: None
    hcp_bucket:
      'goteborg': True
      'linkoping': False
      'umea': False
      'uppsala': False
      'orebro': False
      'stockholm': False
      'lund': False
    lab:
      'Växjö - SE110': True
      'Malmö - SE120': False
      'Kalmar - SE240': False
      'Borås - SE320': False
      'Karlstad - SE450': False
      'Halmstad - SE250': False
      'Trollhättan NÄL - SE310': False
      'Sahlgrenska - SE300': False
      'Karlskrona - SE230': False
      'Visby - SE540': False
      'Karolinska - SE100': False
      'Unilabs - SE130': False
      'SYNLAB - SE140': False
      'Unilabs1 - SE330': False
      'Jönköping - SE350': False
      'Linköping - SE400': False
      'Unilabs2 - SE420': False
      'Västerås - SE430': False
      'Örebro - SE440': False
      'Uppsala - SE600': False
      'Gävle - SE610': False
      'Falun - SE620': False
      'Sundsvall - SE700': False
      'Östersund - SE710': False
      'Umeå - SE720': False
      'Sunderby, Luleå - SE730': False
      'National Pandemic Center - SENPC': False
      'A05diagnostics - SEADG': False
      'ABC lab - SEABC': False
      'Dynamic Code - SEDNC': False
    seq_technology:
      'Illumina': True
      'Nanopore': False
      'Sanger': False
      'Ion Torrent': False
    host:
      'Human': True
      'Environment': False
    library_method:
      'Artic': True
      'NEB': False
      'Midnight': False
  select_multi:
    region:
      'Region Stockholm - 01': True
      'Region Uppsala - 03': False
      'Region Sörmland - 04': False
      'Region Östergötland - 05': False
      'Region Jönköpings län - 06': False
      'Region Kronoberg - 07': False
      'Region Kalmar län - 08': False
      'Region Gotland - 09': False
      'Region Blekinge - 10': False
      'Region Skåne - 12': False
      'Region Halland - 13': False
      'Västra Götalandsregionen - 14': False
      'Region Värmland - 17': False
      'Region Örebro län - 18': False
      'Region Västmanland - 19': False
      'Region Dalarna - 20': False
      'Region Gävleborg - 21': False
      'Region Västernorrland - 22': False
      'Region Jämtland Härjedalen - 23': False
      'Region Västerbotten - 24': False
      'Region Norrbotten - 25': False
    selection_criterion:
      'Allmän övervakning': True
      'Allmän övervakning öppenvård': True
      'Allmän övervakning slutenvård': True
      'Utlandsvistelse': True
      'Vaccinationsgenombrott': True
      'Reinfektion': True
      'Utbrott': True
      'Information saknas': True
    patient_sex:
      'Male': True
      'Female': True
      'Unknown': True
    passage_details_history:
      'Original': True
      'Vero': False
    type:
      'Betacoronavirus': True
      'Unknown': False
    patient_status:
      'Hospitalized': True
      'Released': True
      'Live': True
      'Deceased': True
      'Unknown': True
fx:
  fx:
    fx_path: None


add_empty_selection:
  - fx

filepick_button:
  seq_base_path: True
  csv_base_path: True
  metadata_output_path: True
  metadata_docs_path: True
  pseudo_id_filepath: True
  credentials_filepath: True

tr:
  region_to_code:
    'Region Stockholm - 01': '01'
    'Region Uppsala - 03': '03'
    'Region Sörmland - 04': '04'
    'Region Östergötland - 05': '05'
    'Region Jönköpings län - 06': '06'
    'Region Kronoberg - 07': '07'
    'Region Kalmar län - 08': '08'
    'Region Gotland - 09': '09'
    'Region Blekinge - 10': '10'
    'Region Skåne - 12': '12'
    'Region Halland - 13': '13'
    'Västra Götalandsregionen - 14': '14'
    'Region Värmland - 17': '17'
    'Region Örebro län - 18': '18'
    'Region Västmanland - 19': '19'
    'Region Dalarna - 20': '20'
    'Region Gävleborg - 21': '21'
    'Region Västernorrland - 22': '22'
    'Region Jämtland Härjedalen - 23': '23'
    'Region Västerbotten - 24': '24'
    'Region Norrbotten - 25': '25'
  lab_to_code:
    'Växjö - SE110': 'SE110'
    'Malmö - SE120': 'SE120'
    'Kalmar - SE240': 'SE240'
    'Borås - SE320': 'SE320'
    'Karlstad - SE450': 'SE450'
    'Halmstad - SE250': 'SE250'
    'Trollhättan NÄL - SE310': 'SE310'
    'Sahlgrenska - SE300': 'SE300'
    'Karlskrona - SE230': 'SE230'
    'Visby - SE540': 'SE540'
    'Karolinska - SE100': 'SE100'
    'Unilabs - SE130': 'SE130'
    'SYNLAB - SE140': 'SE140'
    'Unilabs1 - SE330': 'SE330'
    'Jönköping - SE350': 'SE350'
    'Linköping - SE400': 'SE400'
    'Unilabs2 - SE420': 'SE420'
    'Västerås - SE430': 'SE430'
    'Örebro - SE440': 'SE440'
    'Uppsala - SE600': 'SE600'
    'Gävle - SE610': 'SE610'
    'Falun - SE620': 'SE620'
    'Sundsvall - SE700': 'SE700'
    'Östersund - SE710': 'SE710'
    'Umeå - SE720': 'SE720'
    'Sunderby, Luleå - SE730': 'SE730'
    'National Pandemic Center - SENPC': 'SENPC'
    'A05diagnostics - SEADG': 'SEADG'
    'ABC lab - SEABC': 'SEABC'
    'Dynamic Code - SEDNC': 'SEDNC'

upload_complete_file:
  filepath: 'rc/UploadComplete.txt'

seq_files:
  fastq_gz:
    ext: '*.fastq.gz'
    fields:
      fastq: '*.fastq.gz'
  fast5:
    ext: '*.fast5'
    fields:
      fast5: '*.fast5'

fx_functions:
  analytix:
    fun: analytix
    conf: conf.yaml

freetext_filter:
  model_fields:
    - internal_lab_id
    - selection_criterion
    - passage_details_history
    - region
    - patient_sex
    - patient_age
    - patient_status
    - comment

paste_validators:
    model_fields:
      mark: False
      internal_lab_id: False
      selection_criterion:
        qsettings: 'select_multi/selection_criterion'
      collection_date:
        func: date_validate
      patient_age:
        func: age_validate
      patient_sex:
        qsettings: 'select_multi/patient_sex'
      patient_status:
        qsettings: 'select_multi/patient_status'
      type:
        qsettings: 'select_multi/type'
      sminet_lid:
        func: sminet_lid_parser
      pseudo_id: False
      region:
        qsettings: 'select_multi/region'
      region_code: False
      lab:
        qsettings: 'select_single/lab'
      lab_code: False
      host:
        qsettings: 'select_single/host'
      passage_details: True
      seq_technology:
        qsettings: 'select_multi/seq_technology'
      library_method:
        qsettings: 'select_single/library_method'
      lane: False
      fastq: False
      fast5: False
      seq_path: False
      comment: True



