---
model_fields:
  Mark:
    to_meta: False
    col_width: 80
    edit: True
    view: ['patient', 'organism', 'lab']
    checkable: True
    delegates: ['checkbox']
    validators: False
  Internal_lab_ID:
    to_meta: True
    col_width: 100
    edit: False
    view: ['patient', 'organism', 'lab']
    checkable: False
    delegates: ['None']
    validators: ['distinct']
  Selection_criterion:
    to_meta: True
    col_width: 200
    edit: True
    view: ['patient']
    checkable: False
    delegates: ['combobox']
    validators: ['len5']
  Collection_date:
    to_meta: True
    col_width: 100
    edit: True
    view: ['patient']
    checkable: False
    delegates: ['date']
    validators: ['date_format']
  Patient_age:
    to_meta: True
    col_width: 120
    edit: True
    view: [ 'patient' ]
    checkable: False
    delegates: ['age']
    validators: ['age_range']
  Patient_sex:
    to_meta: True
    col_width: 120
    edit: True
    view: [ 'patient' ]
    checkable: False
    delegates: ['combobox']
    validators: ['inlist']
  Patient_status:
    to_meta: True
    col_width: 150
    edit: True
    view: [ 'patient' ]
    checkable: False
    delegates: ['combobox']
    validators: ['inlist']
  Type:
    to_meta: True
    col_width: 100
    edit: True
    view: [ 'patient' ]
    checkable: False
    delegates: ['combobox']
    validators: ['inlist']
  Sminet_LID:
    to_meta: True
    col_width: 100
    edit: True
    view: [ 'lab' ]
    checkable: False
    delegates: [ 'None' ]
    validators: False
  Pseudo_ID:
    to_meta: True
    col_width: 200
    edit: False
    view: ['None']
    checkable: False
    delegates: ['None']
    validators: ['distinct']
  Region:
    to_meta: True
    col_width: 200
    edit: True
    view: ['lab']
    checkable: False
    delegates: ['combobox']
    validators: ['inlist']
  Region_code:
    to_meta: True
    col_width: 200
    edit: True
    view: ['None']
    checkable: False
    delegates: ['None']
    validators: ['inlist']
  Lab:
    to_meta: True
    col_width: 150
    edit: True
    view: ['None']
    checkable: False
    delegates: ['None']
    validators: ['inlist']
  Lab_code:
    to_meta: True
    col_width: 150
    edit: True
    view: [ 'None' ]
    checkable: False
    delegates: [ 'None' ]
    validators: ['inlist']
  Host:
    to_meta: True
    col_width: 100
    edit: True
    view: ['None']
    checkable: False
    delegates: ['None']
    validators: ['len5']
  Passage_details:
    to_meta: True
    col_width: 100
    edit: True
    view: [ 'organism' ]
    checkable: False
    delegates: ['None']
    validators: False
  Sequencing_technology:
    to_meta: True
    col_width: 150
    edit: True
    view: ['None']
    checkable: False
    delegates: ['None']
    validators: ['inlist']
  Library_method:
    to_meta: True
    col_width: 150
    edit: True
    view: ['None']
    checkable: False
    delegates: ['None']
    validators: ['inlist']
  Lane:
    to_meta: True
    col_width: 80
    edit: False
    view: ['lab']
    checkable: False
    delegates: ['None']
    validators: False
  Fastq1:
    to_meta: False
    col_width: 100
    edit: False
    view: ['lab']
    checkable: False
    delegates: ['None']
    validators: False
  Fastq2:
    to_meta: False
    col_width: 100
    edit: False
    view: ['lab']
    checkable: False
    delegates: ['None']
    validators: False
  Fast5:
    to_meta: False
    col_width: 100
    edit: False
    view: [ 'lab' ]
    checkable: False
    delegates: ['None']
    validators: False
  Seq_path:
    to_meta: False
    col_width: 200
    edit: False
    view: ['lab']
    checkable: False
    delegates: ['None']
    validators: False
  Comment:
    to_meta: True
    col_width: 200
    edit: True
    view: ['patient', 'organism', 'lab']
    checkable: False
    delegates: ['None']
    validators: False
settings:
  qlineedits:
    Data_root_path: None
    Metadata_save_path: None
    Pseudo_ID_filepath: None
    Submitter: None
    AWS_key_id: None
    AWS_secret_key: None
    Endpoint: vgtn0008.hcp1.vgregion.se
  qcomboboxes:
    HCP_buckets:
      'goteborg': True
      'linkoping': False
      'umea': False
      'uppsala': False
      'orebro': False
      'stockholm': False
      'lund': False
    Lab:
      'Växjö - SE110': True
      'Malmö - SE120': False
      'Kalmar - SE240': False
      'Borås - SE320': False
      'Karlstad - SE450': False
      'Halmstad - SE250': False
      'Trollhättan NÄL - SE310': False
      'Sahlgrenska - SE300': False
      'Karlskrona - SE230': False
      'Visby - SE540': False
      'Karolinska - SE100': False
      'Unilabs - SE130': False
      'SYNLAB - SE140': False
      'Unilabs1 - SE330': False
      'Jönköping - SE350': False
      'Linköping - SE400': False
      'Unilabs2 - SE420': False
      'Västerås - SE430': False
      'Örebro - SE440': False
      'Uppsala - SE600': False
      'Gävle - SE610': False
      'Falun - SE620': False
      'Sundsvall - SE700': False
      'Östersund - SE710': False
      'Umeå - SE720': False
      'Sunderby, Luleå - SE730': False
      'National Pandemic Center - SENPC': False
      'A05diagnostics - SEADG': False
      'ABC lab - SEABC': False
      'Dynamic Code - SEDNC': False
    Sequencing_technology:
      'Illumina': True
      'Miseq': False
      'Sanger': False
      'Nanopore': False
      'MinION': False
      'Ion Torrent': False
    Host:
      'Human': True
      'Environment': False
    Library_method:
      'Artic': True
      'NEB': False
  qlistwidgets:
    Region:
      'Region Stockholm - 01': True
      'Region Uppsala - 03': False
      'Region Sörmland - 04': False
      'Region Östergötland - 05': False
      'Region Jönköpings län - 06': False
      'Region Kronoberg - 07': False
      'Region Kalmar län - 08': False
      'Region Gotland - 09': False
      'Region Blekinge - 10': False
      'Region Skåne - 12': False
      'Region Halland - 13': False
      'Västra Götalandsregionen - 14': False
      'Region Värmland - 17': False
      'Region Örebro län - 18': False
      'Region Västmanland - 19': False
      'Region Dalarna - 20': False
      'Region Gävleborg - 21': False
      'Region Västernorrland - 22': False
      'Region Jämtland Härjedalen - 23': False
      'Region Västerbotten - 24': False
      'Region Norrbotten - 25': False
    Selection_criterion:
      'Allmän övervakning': True
      'Allmän övervakning öppenvård': True
      'Allmän övervakning slutenvård': True
      'Utlandsvistelse': True
      'Vaccinationsgenombrott': True
      'Reinfektion': True
      'Utbrott': True
      'Information saknas': True
    Patient_sex:
      'Male': True
      'Female': True
      'Unknown': True
    Passage_details_history:
      'Original': True
      'Vero': False
    Type:
      'Betacoronavirus': True
      'Unknown': False
    Patient_status:
      'Hospitalized': True
      'Released': True
      'Live': True
      'Deceased': True
      'Unknown': True
  no_widget:
    Pseudo_ID_start: None
    Pseudo_ID_start_int: None
    Pseudo_ID_start_prefix: None

add_buttons:
  Pseudo_ID_filepath: True
  Data_root_path: True
  Metadata_save_path: True

echomode_password:
  qlineedits:
    AWS_secret_key: True

tr:
  Region_to_code:
    'Region Stockholm - 01': '01'
    'Region Uppsala - 03': '03'
    'Region Sörmland - 04': '04'
    'Region Östergötland - 05': '05'
    'Region Jönköpings län - 06': '06'
    'Region Kronoberg - 07': '07'
    'Region Kalmar län - 08': '08'
    'Region Gotland - 09': '09'
    'Region Blekinge - 10': '10'
    'Region Skåne - 12': '12'
    'Region Halland - 13': '13'
    'Västra Götalandsregionen - 14': '14'
    'Region Värmland - 17': '17'
    'Region Örebro län - 18': '18'
    'Region Västmanland - 19': '19'
    'Region Dalarna - 20': '20'
    'Region Gävleborg - 21': '21'
    'Region Västernorrland - 22': '22'
    'Region Jämtland Härjedalen - 23': '23'
    'Region Västerbotten - 24': '24'
    'Region Norrbotten - 25': '25'
  Lab_to_code:
    'Växjö - SE110': 'SE110'
    'Malmö - SE120': 'SE120'
    'Kalmar - SE240': 'SE240'
    'Borås - SE320': 'SE320'
    'Karlstad - SE450': 'SE450'
    'Halmstad - SE250': 'SE250'
    'Trollhättan NÄL - SE310': 'SE310'
    'Sahlgrenska - SE300': 'SE300'
    'Karlskrona - SE230': 'SE230'
    'Visby - SE540': 'SE540'
    'Karolinska - SE100': 'SE100'
    'Unilabs - SE130': 'SE130'
    'SYNLAB - SE140': 'SE140'
    'Unilabs1 - SE330': 'SE330'
    'Jönköping - SE350': 'SE350'
    'Linköping - SE400': 'SE400'
    'Unilabs2 - SE420': 'SE420'
    'Västerås - SE430': 'SE430'
    'Örebro - SE440': 'SE440'
    'Uppsala - SE600': 'SE600'
    'Gävle - SE610': 'SE610'
    'Falun - SE620': 'SE620'
    'Sundsvall - SE700': 'SE700'
    'Östersund - SE710': 'SE710'
    'Umeå - SE720': 'SE720'
    'Sunderby, Luleå - SE730': 'SE730'
    'National Pandemic Center - SENPC': 'SENPC'
    'A05diagnostics - SEADG': 'SEADG'
    'ABC lab - SEABC': 'SEABC'
    'Dynamic Code - SEDNC': 'SEDNC'
seqfiles:
  fastq_gz:
    ext: '*.fastq.gz'
    fields:
      Fastq1: '*_R1_*'
      Fastq2: '*_R2_*'
  fast5:
    ext: '*.fast5'
    fields:
      Fast5: '*.fast5'

