---
model_fields:
  Mark:
    to_meta: False
    col_width: 80
    edit: True
    view: ['patient', 'organism', 'lab']
    checkable: True
    delegates: ['checkbox']
  Internal_lab_ID:
    to_meta: True
    col_width: 100
    edit: False
    view: ['patient', 'organism', 'lab']
    checkable: False
    delegates: ['None']
  Selection_criterion:
    to_meta: True
    col_width: 200
    edit: True
    view: ['patient']
    checkable: False
    delegates: ['combobox']
  Collection_date:
    to_meta: True
    col_width: 100
    edit: True
    view: ['patient']
    checkable: False
    delegates: ['date']
  Patient_age:
    to_meta: True
    col_width: 120
    edit: True
    view: [ 'patient' ]
    checkable: False
    delegates: ['age']
  Patient_sex:
    to_meta: True
    col_width: 120
    edit: True
    view: [ 'patient' ]
    checkable: False
    delegates: ['combobox']
  Patient_status:
    to_meta: True
    col_width: 150
    edit: True
    view: [ 'patient' ]
    checkable: False
    delegates: ['combobox']
  Type:
    to_meta: True
    col_width: 100
    edit: True
    view: [ 'patient' ]
    checkable: False
    delegates: ['combobox']
  Sminet_LID:
    to_meta: True
    col_width: 100
    edit: True
    view: [ 'lab' ]
    checkable: False
    delegates: [ 'None' ]
  Pseudo_ID:
    to_meta: True
    col_width: 200
    edit: False
    view: ['None']
    checkable: False
    delegates: ['None']
  GISAID_acc:
    to_meta: True
    col_width: 100
    edit: True
    view: ['lab']
    checkable: False
    delegates: ['None']
  Region:
    to_meta: True
    col_width: 200
    edit: True
    view: ['lab']
    checkable: False
    delegates: ['combobox']
  Region_code:
    to_meta: True
    col_width: 200
    edit: True
    view: ['None']
    checkable: False
    delegates: ['None']
  Lab:
    to_meta: True
    col_width: 150
    edit: True
    view: ['None']
    checkable: False
    delegates: ['None']
  Lab_code:
    to_meta: True
    col_width: 150
    edit: True
    view: [ 'None' ]
    checkable: False
    delegates: [ 'None' ]
  Host:
    to_meta: True
    col_width: 100
    edit: True
    view: ['None']
    checkable: False
    delegates: ['None']
  Passage_details:
    to_meta: True
    col_width: 100
    edit: True
    view: [ 'organism' ]
    checkable: False
    delegates: ['None']
  Sequencing_technology:
    to_meta: True
    col_width: 150
    edit: True
    view: ['None']
    checkable: False
    delegates: ['None']
  Library_method:
    to_meta: True
    col_width: 150
    edit: True
    view: ['None']
    checkable: False
    delegates: ['None']
  Lane:
    to_meta: True
    col_width: 80
    edit: False
    view: ['lab']
    checkable: False
    delegates: ['None']
  Fastq1:
    to_meta: False
    col_width: 100
    edit: False
    view: ['lab']
    checkable: False
    delegates: ['None']
  Fastq2:
    to_meta: False
    col_width: 100
    edit: False
    view: ['lab']
    checkable: False
    delegates: ['None']
  Fast5:
    to_meta: False
    col_width: 100
    edit: False
    view: [ 'lab' ]
    checkable: False
    delegates: ['None']
  Seq_path:
    to_meta: False
    col_width: 200
    edit: False
    view: ['lab']
    checkable: False
    delegates: ['None']
  Comment:
    to_meta: True
    col_width: 200
    edit: True
    view: ['patient', 'organism', 'lab']
    checkable: False
    delegates: ['None']
settings:
  qlineedits:
    Data_root_path: None
    Pseudo_ID_filepath: None
    Submitter: None
    AWS_key_id: None
    AWS_secret_key: None
    Endpoint: vgtn0008.hcp1.vgregion.se
  qcomboboxes:
    HCP_buckets:
      'goteborg': True
      'linkoping': False
      'umea': False
      'uppsala': False
      'orebro': False
      'stockholm': False
      'lund': False
    Lab:
      'Växjö - SE110': True
      'Malmö - SE120': False
      'Kalmar - SE240': False
      'Borås - SE320': False
      'Karlstad - SE450': False
      'Halmstad - SE250': False
      'Trollhättan NÄL - SE310': False
      'Sahlgrenska - SE300': False
      'Karlskrona - SE230': False
      'Visby - SE540': False
      'Karolinska - SE100': False
      'Unilabs - SE130': False
      'SYNLAB - SE140': False
      'Unilabs1 - SE330': False
      'Jönköping - SE350': False
      'Linköping - SE400': False
      'Unilabs2 - SE420': False
      'Västerås - SE430': False
      'Örebro - SE440': False
      'Uppsala - SE600': False
      'Gävle - SE610': False
      'Falun - SE620': False
      'Sundsvall - SE700': False
      'Östersund - SE710': False
      'Umeå - SE720': False
      'Sunderby, Luleå - SE730': False
      'National Pandemic Center - SENPC': False
      'A05diagnostics - SEADG': False
      'ABC lab - SEABC': False
      'Dynamic Code - SEDNC': False
    Sequencing_technology:
      'Illumina': True
      'Miseq': False
      'Sanger': False
      'Nanopore': False
      'MinION': False
      'Ion Torrent': False
    Host:
      'Human': True
      'Environment': True
    Library_method:
      'Artic': True
      'NEB': False
  qlistwidgets:
    Region:
      'Region Stockholm - 01': True
      'Region Uppsala - 03': False
      'Region Sörmland - 04': False
      'Region Östergötland - 05': False
      'Region Jönköpings län - 06': False
      'Region Kronoberg - 07': False
      'Region Kalmar län - 08': False
      'Region Gotland - 09': False
      'Region Blekinge - 10': False
      'Region Skåne - 12': False
      'Region Halland - 13': False
      'Västra Götalandsregionen - 14': False
      'Region Värmland - 17': False
      'Region Örebro län - 18': False
      'Region Västmanland - 19': False
      'Region Dalarna - 20': False
      'Region Gävleborg - 21': False
      'Region Västernorrland - 22': False
      'Region Jämtland Härjedalen - 23': False
      'Region Västerbotten - 24': False
      'Region Norrbotten - 25': False
    Selection_criterion:
      'Allmän övervakning': True
      'Allmän övervakning öppenvård': True
      'Allmän övervakning slutenvård': True
      'Utlandsvistelse': True
      'Vaccinationsgenombrott': True
      'Reinfektion': True
      'Utbrott': True
      'Information saknas': True
    Patient_sex:
      'Male': True
      'Female': True
      'Unknown': True
    Passage_details_history:
      'Original': True
      'Vero': False
    Type:
      'Betacoronavirus': True
      'Unknown': False
    Patient_status:
      'Hospitalized': True
      'Released': True
      'Live': True
      'Deceased': True
      'Unknown': True
  no_widget:
    Pseudo_ID_start: None

add_buttons:
  Pseudo_ID_filepath: True
  Data_root_path: True

echomode_password:
  qlineedits:
    AWS_secret_key: True

translations:
  Region:
    'Region Stockholm - 01':
      Region_code: '01'
    'Region Uppsala - 03':
      Region_code: '03'
    'Region Sörmland - 04':
      Region_code: '04'
    'Region Östergötland - 05':
      Region_code: '05'
    'Region Jönköpings län - 06':
      Region_code: '06'
    'Region Kronoberg - 07':
      Region_code: '07'
    'Region Kalmar län - 08':
      Region_code: '08'
    'Region Gotland - 09':
      Region_code: '09'
    'Region Blekinge - 10':
      Region_code: '10'
    'Region Skåne - 12':
      Region_code: '12'
    'Region Halland - 13':
      Region_code: '13'
    'Västra Götalandsregionen - 14':
      Region_code: '14'
    'Region Värmland - 17':
      Region_code: '17'
    'Region Örebro län - 18':
      Region_code: '18'
    'Region Västmanland - 19':
      Region_code: '19'
    'Region Dalarna - 20':
      Region_code: '20'
    'Region Gävleborg - 21':
      Region_code: '21'
    'Region Västernorrland - 22':
      Region_code: '22'
    'Region Jämtland Härjedalen - 23':
      Region_code: '23'
    'Region Västerbotten - 24':
      Region_code: '24'
    'Region Norrbotten - 25':
      Region_code: '25'
  Lab:
    'Växjö - SE110':
      Lab_code: 'SE110'
    'Malmö - SE120':
      Lab_code: 'SE120'
    'Kalmar - SE240':
      Lab_code: 'SE240'
    'Borås - SE320':
      Lab_code: 'SE320'
    'Karlstad - SE450':
      Lab_code: 'SE450'
    'Halmstad - SE250':
      Lab_code: 'SE250'
    'Trollhättan NÄL - SE310':
      Lab_code: 'SE310'
    'Sahlgrenska - SE300':
      Lab_code: 'SE300'
    'Karlskrona - SE230':
      Lab_code: 'SE230'
    'Visby - SE540':
      Lab_code: 'SE540'
    'Karolinska - SE100':
      Lab_code: 'SE100'
    'Unilabs - SE130':
      Lab_code: 'SE130'
    'SYNLAB - SE140':
      Lab_code: 'SE140'
    'Unilabs1 - SE330':
      Lab_code: 'SE330'
    'Jönköping - SE350':
      Lab_code: 'SE350'
    'Linköping - SE400':
      Lab_code: 'SE400'
    'Unilabs2 - SE420':
      Lab_code: 'SE420'
    'Västerås - SE430':
      Lab_code: 'SE430'
    'Örebro - SE440':
      Lab_code: 'SE440'
    'Uppsala - SE600':
      Lab_code: 'SE600'
    'Gävle - SE610':
      Lab_code: 'SE610'
    'Falun - SE620':
      Lab_code: 'SE620'
    'Sundsvall - SE700':
      Lab_code: 'SE700'
    'Östersund - SE710':
      Lab_code: 'SE710'
    'Umeå - SE720':
      Lab_code: 'SE720'
    'Sunderby, Luleå - SE730':
      Lab_code: 'SE730'
    'National Pandemic Center - SENPC':
      Lab_code: 'SENPC'
    'A05diagnostics - SEADG':
      Lab_code: 'SEADG'
    'ABC lab - SEABC':
      Lab_code: 'SEABC'
    'Dynamic Code - SEDNC':
      Lab_code: 'SEDNC'
seqfiles:
  fastq_gz:
    ext: '*.fastq.gz'
    fields:
      Fastq1: '*_R1_*'
      Fastq2: '*_R2_*'
  fast5:
    ext: '*.fast5'
    fields:
      Fast5: '*.fast5'

