---
fields:
    internt_labid:
        distinct: True
    urvalskriterium:
        white_trail: True
        white_lead: True
    datum:
        date_pattern: '%Y-%m-%d'
    GISAID_accession:
        pattern: 'EP\d{7}'
    filer:
        distinct: True
        pattern: '^.*_R1_*.fastq.gz;.*_R2_*.fastq.gz$|^.*_R1_*.fastq.gz$'
    regionkod:
        list:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
            - 12
            - 13
            - 14
            - 17
            - 18
            - 19
            - 20
            - 21
            - 22
            - 23
            - 24
            - 25
    labkod:
        list:
            - "SE110"
            - "SE120"
            - "SE240"
            - "SE320"
            - "SE450"
            - "SE250"
            - "SE310"
            - "SE300"
            - "SE230"
            - "SE540"
            - "SE100"
            - "SE130"
            - "SE140"
            - "SE330"
            - "SE350"
            - "SE400"
            - "SE420"
            - "SE430"
            - "SE440"
            - "SE600"
            - "SE610"
            - "SE620"
            - "SE700"
            - "SE710"
            - "SE720"
            - "SE730"
            - "SENPC"
            - "SEADG"
            - "SEABC"
            - "SEDNC"
    instrument:
        list:
            - "miseq"
            - "nanopore"
            - "novaseq"
    plattform:
        list:
            - "qiagen"
            - "illumina"
            - "oxford nanopore"
    biblioteksmetod:
        list:
            - "bla bla"
            - "asdf"


